### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by iferres** [larssnip/micropan#1]
Hi, I got the following when installing micropan:
`> devtools::install_github('larssnip/micropan')
Downloading GitHub repo larssnip/micropan@master
from URL https://api.github.com/repos/larssnip/micropan/zipball/master
Installing micropan
'/usr/lib64/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpEARWw2/devtools4815197462c8/larssnip-micropan-90d063a'  \
  --library='/home/user/R/x86_64-redhat-linux-gnu-library/3.3' --install-tests 

* installing *source* package ‘micropan’ ...
** libs
g++ -m64 -shared -L/usr/lib64/R/lib -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -o micropan.so ORF_index.o RcppExports.o extractORF.o -L/usr/lib64/R/lib -lR
ORF_index.o: file not recognized: File format is ambiguous
ORF_index.o: matching formats: coff-x86-64 pe-x86-64
collect2: error: ld returned 1 exit status
/usr/share/R/make/shlib.mk:6: recipe for target 'micropan.so' failed
make: *** [micropan.so] Error 1
ERROR: compilation failed for package ‘micropan’
* removing ‘/home/user/R/x86_64-redhat-linux-gnu-library/3.3/micropan’
Installation failed: Command failed (1)`

Any idea on what's going on? I got a very similar message in a different computer.
Thanks!

**Comment by khliland** [comment]
Hi iferres.
The repository is not fully cleaned from extra local compilation files, which I suspect is the source of this error. I would recommend installing from CRAN instead for the time being. We will make sure to clean this up with coming updates.
Best regards,
khliland

**Comment by iferres** [comment]
Thanks Khliland, 
I tried using the CRAN version first but I notice that there's a bug on the `hmmerScan()` function, which you have already corrected on this repo. That's why I was trying to install this one. At the end I use the corrected version of the function (the one here) with the other functions available on the CRAN version of the package.
Thanks for your time.
Bests, 
Ignacio
