### ISSUE TITLE
hi. i can't solve this problems (Column 'V2' not found in ',data'

### ISSUE THREAD

**Issue by byeollee** [larssnip/micropan#6]
When I try to get distances by bDIst()

`dst.tbl <- bDist(file.path("blast1", list.files("blast1", pattern = "txt$")))`

I get a error message :

bDist:
...reading 2 self alignments...
error: Column `V2` not found in `.data`
Run `rlang::last_error()` to see where the error occurred.

and also i am showing the file list blast1 :
/home/star/blast1/GID1_vs_GID1.txt
/home/star/blast1/GID10_vs_GID1.txt
/home/star/blast1/GID11_vs_GID1.txt
/home/star/blast1/GID12_vs_GID1.txt
/home/star/blast1/GID13_vs_GID1.txt
/home/star/blast1/GID14_vs_GID1.txt
/home/star/blast1/GID15_vs_GID1.txt
/home/star/blast1/GID16_vs_GID1.txt
/home/star/blast1/GID17_vs_GID1.txt
/home/star/blast1/GID100_vs_GID1.txt
/home/star/blast1/GID101_vs_GID1.txt
/home/star/blast1/GID102_vs_GID1.txt
/home/star/blast1/GID103_vs_GID1.txt
/home/star/blast1/GID104_vs_GID1.txt
/home/star/blast1/GID105_vs_GID1.txt
/home/star/blast1/GID106_vs_GID1.txt
/home/star/blast1/GID107_vs_GID1.txt
/home/star/blast1/GID108_vs_GID1.txt
/home/star/blast1/GID109_vs_GID1.txt
/home/star/blast1/GID110_vs_GID1.txt
/home/star/blast1/GID111_vs_GID1.txt
/home/star/blast1/GID112_vs_GID1.txt
/home/star/blast1/GID113_vs_GID1.txt
/home/star/blast1/GID114_vs_GID1.txt
/home/star/blast1/GID115_vs_GID1.txt
/home/star/blast1/GID116_vs_GID1.txt
/home/star/blast1/GID117_vs_GID1.txt
/home/star/blast1/GID118_vs_GID1.txt ... etc

Total 84 txt file, I want to analysis these all.

Please help

Thank you

**Comment by larssnip** [comment]
OK, its holiday times here, but I will try to have a look at this in the weekend.


LS

**Comment by larssnip** [comment]
Could you please email me the file GID1_vs_GID1.txt?

The error message also indicates there is something else wrong here. It says it finds 2 self-alignment files. There should be many more, right? All genomes should have a self-alignment BLAST-file. The listing above contains 28 different genomes (GID1, GID10, GID11...etc). All of them should have a self-alignment file (GID10_vs_GID10.txt, GID11_vs_GID11.txt...etc). How many genomes are in this study?

**Comment by byeollee** [comment]
Wow.. Thank you for your kindness

I hope that you spent your holiday well :)
 
When I try to get only two genome file, My problems is not coming

Could you tell me that how many genome we can analysis??

I try to get blast results from 289 genome file again.

Thank you so much

**Comment by larssnip** [comment]
Hi,

The number of genomes is only limited by your time and your computer memory.

Try to start with a few genomes. Run the blastpAllAll, and the rest of the procedure, to verify it works. Then add a few more genomes, and re-run. Use the same folders, both for the genomes and the blast results.

With N genomes there should always be N self-alignments files, i.e. blast results files where a genome is compared against itself.


LS
